### ISSUE TITLE
Unable to run dev build locally

### ISSUE THREAD

**Issue by scrapcupcake** [Tonejs/ui#1]
Hi there. I was gonna get digging into this project, but I can't get the basic dev tools to run on my windows machine. My output is below. Probably a non-js requirement that I'm not understanding I need  😁 

```
[3/4] Linking dependencies...
[4/4] Building fresh packages...[1/3] ⠄ node-sass
[2/3] ⠄ puppeteer
error C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Hunnie Tana\\Desktop\\Projects\\toneui\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.11.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\isexe\windows.js:36:5gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\isexe\windows.js:36:5gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\Hunnie Tana\\Desktop\\Projects\\toneui\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Hunnie Tana\\Desktop\\Projects\\toneui\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Hunnie Tana\\Desktop\\Projects\\toneui\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Hunnie Tana\\Desktop\\Projects\\toneui\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Hunnie Tana\\Desktop\\Projects\\toneui\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Hunnie Tana\\Desktop\\Projects\\toneui\\node_modules\\isexe\\windows.js:36:5\n
  at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Program Files\Python36\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:275:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hunnie Tana\\Desktop\\Projects\\toneui\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Hunnie Tana\Desktop\Projects\toneui\node_modules\node-sass
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by scrapcupcake** [comment]
I appear to have gotten around the issue; the above was from running yarn install. Running npm install appears to be doing the trick!
